import { SafetyCategory } from "./safety.types";

/**
 * Built-in safety-keywords (RU+EN). Триггер — substring совпадение в нормализованном
 * тексте (lowercase, ё→е). Подобраны как корни/частые формы — компромисс между
 * полнотой и шумом (морфологически точнее — отдельная задача).
 *
 * Бот opt-in через guardrails.safetyChecks: ["medical", ...].
 */
export const SAFETY_KEYWORDS: Record<Exclude<SafetyCategory, "injection">, string[]> = {
  medical: [
    "лечить",
    "лечение",
    "вылечить",
    "лечу",
    "болит",
    "болезн",
    "болен",
    "больной",
    "больна",
    "симптом",
    "диагноз",
    "лекарств",
    "таблетк",
    "препарат",
    "дозировк",
    "температур",
    "аллерги",
    "сыпь",
    "зуд",
    "противопоказ",
    "психотерап",
    "psychiat",
    "treatment",
    "diagnos",
    "medic",
    "prescription",
    "symptom",
    "allergy",
  ],
  legal: [
    "иск",
    "исковое",
    "судебн",
    "договор",
    "контракт",
    "юрист",
    "адвокат",
    "правонаруш",
    "законн",
    "нелегальн",
    "lawsuit",
    "legal advice",
    "attorney",
    "lawyer",
    "contract",
  ],
  financial: [
    "инвестиц",
    "инвестир",
    "вложить деньг",
    "куда вложить",
    "куда инвест",
    "лучше инвест",
    "стоит инвест",
    "акци",
    "облигац",
    "крипт",
    "биткоин",
    "трейд",
    "форекс",
    "брокер",
    "доходност",
    "дивиденд",
    "invest",
    "stock",
    "crypto",
    "bitcoin",
    "trading",
    "forex",
  ],
  self_harm: [
    "суицид",
    "покончить с собой",
    "не хочу жить",
    "убить себя",
    "selfharm",
    "suicide",
    "kill myself",
  ],
};
